tunnel: your-tunnel-name
credentials-file: /etc/cloudflared/credentials.json
ingress:
  - hostname: esimochatbot.ru
    service: http://127.0.0.1:8505  # Или host.docker.internal:8505
  - service: http_status:404  # Для всех остальных запросов